name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
            - name: Setup Lua/LuaJIT
  # You may pin to the exact commit or the version.
  # uses: xpol/setup-lua@84f642e19a1adbad98b74f9e69ab82d1e6b95e3e
  uses: xpol/setup-lua@v0.3
  with:
    # The version of Lua to install. Supported versions: Lua >= 5.1.0, LuaJIT >= 2.0.0
    lua-version: # optional, default is 5.3.5
    # Optional: The target platform (e.g. -A Win32 | x64).
    platform: # optional
                        - name: Setup Haxe environment
                uses: krdlab/setup-haxe@v1.5.1
                          - name: CURL-ACTION
                uses: enflo/curl-action@1.3
            
